---
# Source: rhoai-gitops/templates/operators/10-nfd-operator.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
# Source: rhoai-gitops/templates/operators/20-gpu-operator.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
# Source: rhoai-gitops/templates/operators/30-rhoai-operator.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
# Source: rhoai-gitops/templates/configs/32-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "32"
spec:
  replicas: 1
---
# Source: rhoai-gitops/templates/configs/35-dashboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhods-dashboard
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  replicas: 1
---
# Source: rhoai-gitops/templates/configs/25-gpu-clusterpolicy.yaml
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "25"
spec:
  vgpuDeviceManager:
    config:
      default: default
    enabled: true
  migManager:
    config:
      default: all-disabled
      name: default-mig-parted-config
    enabled: true
  operator:
    defaultRuntime: crio
    initContainer: {}
    runtimeClass: nvidia
    use_ocp_driver_toolkit: true
  dcgm:
    enabled: true
  gfd:
    enabled: true
  dcgmExporter:
    config:
      name: ''
    enabled: true
    serviceMonitor:
      enabled: true
  cdi:
    default: false
    enabled: false
  driver:
    licensingConfig:
      configMapName: ''
      nlsEnabled: true
    enabled: true
    kernelModuleType: proprietary
    useOpenKernelModules : false
    certConfig:
      name: ''
    useNvidiaDriverCRD: false
    kernelModuleConfig:
      name: ''
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: false
        enable: false
        force: false
        timeoutSeconds: 300
      maxParallelUpgrades: 1
      maxUnavailable: 25%
      podDeletion:
        deleteEmptyDir: false
        force: false
        timeoutSeconds: 300
      waitForCompletion:
        timeoutSeconds: 0
    repoConfig:
      configMapName: ''
    virtualTopology:
      config: ''
  devicePlugin:
    config:
      default: ''
      name: ''
    enabled: true
    mps:
      root: /run/nvidia/mps
  gdrcopy:
    enabled: false
  kataManager:
    config:
      artifactsDir: /opt/nvidia-gpu-operator/artifacts/runtimeclasses
  mig:
    strategy: single
  sandboxDevicePlugin:
    enabled: true
  validator:
    plugin:
      env:
        - name: WITH_WORKLOAD
          value: 'false'
  nodeStatusExporter:
    enabled: true
  daemonsets:
    rollingUpdate:
      maxUnavailable: '1'
    updateStrategy: RollingUpdate
  sandboxWorkloads:
    defaultWorkload: container
    enabled: false
  gds:
    enabled: false
  vgpuManager:
    enabled: false
  vfioManager:
    enabled: true
  toolkit:
    enabled: true
    installDir: /usr/local/nvidia
---
# Source: rhoai-gitops/templates/configs/32-datascienceclusterinitialization.yaml
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: default-dsci
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "32"
spec:
  dataScienceClusterInitialization:
    serviceMesh:
      managementState:
---
# Source: rhoai-gitops/templates/configs/33-datasciencecluster.yaml
apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "33"
  namespace: redhat-ods-applications
spec:
  components:
    codeflare:
      managementState: Removed
    dashboard:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    kserve:
      defaultDeploymentMode: RawDeployment
      managementState: Managed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headed
      serving:
        ingressGateway:
          certificate:
            type: OpenshiftDefaultIngress
        managementState: Removed
        name: knative-serving
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Unmanaged
    llamastackoperator:
      managementState: Managed
    modelmeshserving:
      managementState: Removed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    ray:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    trustyai:
      managementState: Managed
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
---
# Source: rhoai-gitops/templates/configs/15-nfd-instance.yaml
# Creates an instance of NodeFeatureDiscovery, which deploys the worker pods
apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "15"
spec:
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
---
# Source: rhoai-gitops/templates/configs/35-odhdashboardconfig.yaml
apiVersion: opendatahub.io/v1alpha
kind: OdhDashboardConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "35"
  labels:
    app.kubernetes.io/part-of: rhods-dashboard
    app.opendatahub.io/rhods-dashboard: "true"
  name: odh-dashboard-config
  namespace: redhat-ods-applications
spec:
  dashboardConfig:
  groupsConfig:
    adminGroups: rhods-admins
    allowedGroups: system:authenticated
  modelServerSizes:
    - name: Small
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 4Gi
    - name: Medium
      resources:
        limits:
          cpu: "8"
          memory: 10Gi
        requests:
          cpu: "4"
          memory: 8Gi
    - name: Large
      resources:
        limits:
          cpu: "10"
          memory: 20Gi
        requests:
          cpu: "6"
          memory: 16Gi
  notebookSizes:
    - name: Small
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 8Gi
    - name: Medium
      resources:
        limits:
          cpu: "6"
          memory: 24Gi
        requests:
          cpu: "3"
          memory: 24Gi
    - name: Large
      resources:
        limits:
          cpu: "14"
          memory: 56Gi
        requests:
          cpu: "7"
          memory: 56Gi
    - name: X Large
      resources:
        limits:
          cpu: "30"
          memory: 120Gi
        requests:
          cpu: "15"
          memory: 120Gi
  notebookController:
    enabled: true
    notebookNamespace: rhods-notebooks
    pvcSize: 20Gi
  templateDisablement: []
  templateOrder: []
---
# Source: rhoai-gitops/templates/operators/10-nfd-operator.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nfd-group
  namespace: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  targetNamespaces:
  - openshift-nfd
---
# Source: rhoai-gitops/templates/operators/20-gpu-operator.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nvidia-gpu-operator-group
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  targetNamespaces:
  - nvidia-gpu-operator
---
# Source: rhoai-gitops/templates/operators/30-rhoai-operator.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-ods-operator-group
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec: {}
---
# Source: rhoai-gitops/templates/operators/10-nfd-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  namespace: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Source: rhoai-gitops/templates/operators/20-gpu-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: gpu-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
# Source: rhoai-gitops/templates/operators/30-rhoai-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  channel: fast-3.x
  installPlanApproval: Automatic
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
